"""check move base to app.models (no-op)."""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1dbcbe9837a6'
down_revision: Union[str, Sequence[str], None] = '40c13b316c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
