"""users: contacts optional + email/phone check."""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '40c13b316c44'
down_revision: Union[str, Sequence[str], None] = '4cc957b686cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
