"""users: contacts optional + email/phone check."""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4cc957b686cb'
down_revision: Union[str, Sequence[str], None] = 'b0784497fbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'email',
        existing_type=sa.VARCHAR(length=254),
        nullable=True,
    )
    op.alter_column(
        'users',
        'phone',
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    op.alter_column(
        'users',
        'tg_id',
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'tg_id',
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        'users',
        'phone',
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.alter_column(
        'users',
        'email',
        existing_type=sa.VARCHAR(length=254),
        nullable=False,
    )
    # ### end Alembic commands ###
