"""cafes + cafe_manager."""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '740679b7ecd8'
down_revision: Union[str, Sequence[str], None] = '1dbcbe9837a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cafe_manager',
        sa.Column('cafe_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('cafe_id', 'user_id'),
        sa.UniqueConstraint(
            'cafe_id',
            'user_id',
            name='uq_cafe_manager_cafe_user',
        ),
    )
    op.create_table(
        'cafes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafes')
    op.drop_table('cafe_manager')
    # ### end Alembic commands ###
