"""slots_id, tables_id by Booking model

Revision ID: 443c6ada05e1
Revises: 740113856925
Create Date: 2025-10-21 20:16:32.637677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443c6ada05e1'
down_revision: Union[str, Sequence[str], None] = '740113856925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'photo_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cafes', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('cafes', 'photo_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cafes', 'photo_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cafes', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('actions', 'photo_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
