"""slots_id, tables_id back_populates in models

Revision ID: d15d3aec043f
Revises: 443c6ada05e1
Create Date: 2025-10-21 20:32:15.165375

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd15d3aec043f'
down_revision: Union[str, Sequence[str], None] = '443c6ada05e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
