"""cafe-table

Revision ID: f36e748b4beb
Revises: 740113856925
Create Date: 2025-10-22 18:55:59.532709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36e748b4beb'
down_revision: Union[str, Sequence[str], None] = '740113856925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'photo_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cafes', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('cafes', 'photo_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cafes', 'photo_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cafes', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('actions', 'photo_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
